# This workflow will check the python code using black

name: Python style check

on:
  push:
    branches: [master]
    paths:
    - 'controller/**'
    - 'policy/**'
    - '.github/workflows/python.yml'
  pull_request:
    branches: [master]
    paths:
    - 'controller/**'
    - 'policy/**'
    - '.github/workflows/python.yml'

jobs:
  style-check:
    name: Python style check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: clonedSemicolon/setup-strace@v13
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install 'black[jupyter]~=23.0'
    - name: Check style
      run: |
        black --check .
    - name: Upload strace artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strace-logs-${{ github.job }}-${{ matrix.flavor || 'lint' }}-${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index || 0 }}
        path: /home/runner/strace_logs/
